Webshop/Webshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls.conf import include
from .views import *


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop.urls")),
    # path('', index, name='index')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Webshop/shop/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.urls import reverse
from . import views
from .views import *
import Webshop

app_name = "shop"

urlpatterns = [
    path("", products, name="index"),
    path("shopping_cart/", ShoppingCartView.as_view(), name="shopping_cart"),
    path("product/<pk>/", ProductView.as_view(), name="product"),
    url(r"^(?P<id>[\w-]+)/$", views.ProductView.as_view(), name="product"),
    path("product/<pk>/add_to_cart/", add_to_cart, name="add_to_cart"),
    path("product/<pk>/remove_from_cart/", remove_from_cart, name="remove_from_cart"),
    path('shopping_cart/checkout/', CheckoutView.as_view(), name='checkout'),
    path('<pk>/update_quantity/', update_quantity, name='update_quantity')

]

Webshop/templates/base.html
{% load static %}  
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Webshop</title>  
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="#" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> 
    <link href="{% static 'css/bootstrap-grid.css' %}" >  
    <link href="{% static 'css/bootstrap-grid.css.map' %}" >
    <link href="{% static 'css/bootstrap-reboot.css' %}" >
    <link href="{% static 'css/bootstrap-reboot.css.map' %}" >
    <link href="{% static 'css/bootstrap-reboot.min.css.map' %}" >
    <link href="{% static 'css/bootstrap-reboot.min.css' %}" >
    <link href="{% static 'css/bootstrap.min.css' %}" >  
    <link href="{% static 'css/bootstrap.css' %}" >  
    <link href="{% static 'css/bootstrap.css.map' %}" > 
    <link href="{% static 'css/bootstrap.min.css' %}" > 
    <link href="{% static 'css/bootstrap.min.css.map' %}" > 
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js.map' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <link href="{% static 'more_css/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'more_css/css/mdb.min.css' %}" rel="stylesheet">
  <link href=" {% static 'more_css/css/style.min.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
   
  <style type="text/css">
          html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

      body {
    margin-top: 25px;
    margin-bottom: 25px;
    margin-left: 25px;
    margin-right: 25px;
      }
      .md-form.mt-0{
    display:inline-flex;
    width:500px;
    float: "right";
    } 

    .searchBar  {
    position:relative;
    left:20%;
    top:25%;
    width:30%;
    width:300px;
    background-color: aliceblue;
   
    }
.searchbar input[type="text"]{
   color: aliceblue;
}
.searchbar {
  margin-left: 35px;
  width: 500px;
}
.welcome{
    margin-left: 35px;
}
.cart_icon {
    margin-left: 35px;
    margin-top: 18px;
}
.link_to_shopping_cart {
    margin-top: 18px;
}
.sr-only{
    margin-top: 18px;
}

  </style>
</head>  
<body>  
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <img src="{% static 'webshop_logo.jpg' %}" height="120" alt="logo">
        <div class="welcome"></div>
        <a class="navbar-brand" href="{% url 'shop:index' %}">    @Welcome to Webshop!</a> 
        <div class="container">

           
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'shop:index' %}" >Home <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                <div class="searchbar">
                <form class="form-inline my-2 my-lg-0" action="{% url 'shop:index' %}"  ame="product_name"   method="GET" action="{% url 'shop:index' %}"  >
                  <div class="md-form my-0"> 
                  <input id='keyword'  width="20px "class="form-control mr-sm-2"  name="name" type="text" placeholder="Search by name/code" aria-label="Search"  onmousedown="postNameData();">
                  <i class="material-icons mdc-button__icon">
                  <input type="submit" value="search" onmousedown="postNameData();">
              </i>
              </div>
              </form>
            </div>
                <ul class="navbar-nav nav-flex-icons">
                    <div class="link_to_shopping_cart">
                    <li class="nav-item active">
                        {% if "shop:shopping_cart" %}
                     <a class="nav-link"  href="{% url 'shop:shopping_cart' %}" class="btn" >Shopping Cart
      
                      <i class="fas fa-shopping-cart"></i></a> 
                      {% endif %}
                      <span class="clearfix d-none d-sm-inline-block"> </span>
                  </li>
                </div>
                    <li class="nav-item">
                          <span class="badge  z-depth-1 mr-1">  </span>
                        <button class="cart_icon">     
                        <i class="fas fa-shopping-cart"  aria-hidden="true" ></i> {{ object.get_items_total}} {{items}} </button> 
                        <span class="clearfix d-none d-sm-inline-block">  </span>
                        </a>
                    </li>
               
                    <span class="sr-only">(current)</span>
                    <li class="nav-item">
                         <a class="nav-link waves-effect">
                        Hello, {{ user.username }}!
                        </a>
                    </li>
        
                </ul>
           
            </div>
        </div>
    </nav>
    {% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}
    {% block content %}
    <script type="text/javascript">

      function postNameData() {
        var product_name = document.getElementById("keyword").value
          var data = {product_name: product_name};
        $.ajax({
          type: "GET",
          url: "{% url 'shop:index' %}",
          data: JSON.stringify(data),
          success: function(data){
              console.log("success");
              location.reload();
              console.log(data);
          },
          failure: function(data){
              console.log("failure");
              console.log(data);
          },
      });
      }
      
        </script>
    {% endblock %}

</body>  
</html>

Webshop/templates/index.html
{% extends "base.html" %}
{% load static %}
<head>
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
  <script src='https://code.jquery.com/jquery-3.3.1.min.js'></script>
  <script src="/lib/jquery.plugin.js"></script>
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
  <script src='https://code.jquery.com/jquery-3.3.1.min.js'></script>
  <script src="/lib/jquery.plugin.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
 <style>
   .SearchBar {
     position: absolute;
     top: 355px;
     left: 575px;
}

.SearchBar input {
   position: absolute;
     height: 30px;
     width: 150px;
}
.md-form.mt-0{
  width:400px;
  display:flex;
  align-items: center;  
}

.material-icons.mdc-button__icon{
  position:absolute;
}

.mdc-button__icon + input{
  width: 200px;
  padding-left: 25px;
}
.img-wrap {
  width: 200px;
  height: 150px;
  position: relative;
  display: inline-block;
  overflow: hidden;
  margin: 0;
}
.happy shopping {
  float: "right";
}
 </style>
</head>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

{% block content %}


<div class="grid-wrapper">
<div>

</div>


  </div>
    <script src="//code.jquery.com/jquery-1.9.1.min.js"></script>
    <script type="text/javascript">

function postNameData() {
  var product_name = document.getElementById("keyword").value
    var data = {product_name: product_name};
  $.ajax({
    type: "GET",
    url: "{% url 'shop:index' %}",
    data: JSON.stringify(data),
    success: function(data){
        console.log("success");
        // location.reload();
        console.log(data);
    },
    failure: function(data){
        console.log("failure");
        console.log(data);
    },
});
}

  </script>
   <div class="row">
{% for product in product_list %}
<!-- 
<div class="grid-item"> -->

  <div class="col-sm-6 col-md-4">
    <div class="animate-bottom thumbnail">
      
<div class="view overlay">
  <p></p>
    <h5 class="card-title">{{ product.product_name.title }}</h5>
    <div class="img-wrap">
    <img class="img-responsive" height="250" src="{{product.image.url}}" alt="{{product}}">
    </div>
    <br />
    <a href="{{ product.view_product}}"  class="blue-text">Shop now!
      <div class="mask rgba-white-slight"></div>
    </a>
  
<div float='left' class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{ product.product_name.title }}</h5>
    <p class="card-text">{{ product.description }}</p>
    <p class="card-text">Price - {{ product.price }} €</p>
    <a href="{{ product.view_product}}" class="btn btn-primary">See more</a>
  </div>
  </div>
</div>
</div>
</div>
{% endfor %}
</div>
<div class="happy_shopping">
<h6 class="my-5 h2 text-right">Happy Shopping, {{ user.username }}! </h6>
</div>
</div>
{% endblock content %}

Webshop/templates/product-page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Material Design Bootstrap</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="css/mdb.min.css" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="css/style.min.css" rel="stylesheet">
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">


      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="https://mdbootstrap.com/docs/jquery/" target="_blank">About MDB</a>
          </li>
       
  
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> 1 </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a href="https://www.facebook.com/mdbootstrap" class="nav-link waves-effect" target="_blank">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="https://twitter.com/MDBootstrap" class="nav-link waves-effect" target="_blank">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">Category 2</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            </div>

            <p class="lead">
              <span class="mr-1">
                <del>$200</del>
              </span>
              <span>$100</span>
            </p>

            <p class="lead font-weight-bold">Description</p>

            <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p> 
        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank"
        role="button">Download MDB
        <i class="fas fa-download ml-2"></i>
      </a>
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">Start
        free tutorial
        <i class="fas fa-graduation-cap ml-2"></i>
      </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="js/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="js/mdb.min.js"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>

{% endblock content %}

Webshop/templates/product.html
{% extends 'product-page.html' %}
{% load static %}
<head>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
    <script src='https://code.jquery.com/jquery-3.3.1.min.js'></script>
    <script src="/lib/jquery.plugin.js"></script>
   
</head>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

{% block content %}
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
      <div class="row wow fadeIn">
        <div class="col-md-6 mb-4">

    <H6 class="lead font-weight-bold">{{ object.product_name.title }}</H6>
    <img src="{{product.image.url}}" alt="product" width="350" height="450"  class="img-fluid" >
</div>
        <div class="col-md-6 mb-4">
          <div class="p-4">
            <p class="lead">
                {% csrf_token %}
        <script>
            var url = "add_to_cart/"
           
            var cartItem = `{{product.id}}`
            var data = {
                cartItem: cartItem
            };
        </script>
        <div float="left">
        <button id="add_button" background-color='#008CBA'  width="18em"  class="btn btn-primary btn-md my-0 p" onClick="postData(url, data);doNext()"> Add {{ object.product_name }} to cart 
            <i class="fas fa-shopping-cart ml-1"></i>
        </button> 
        </div>
        <script type="text/javascript">
      
            // document.getElementById("add_button").onclick = function () {
            //     location.href = "{% url 'shop:shopping_cart'%}" ;
            // }
        </script>
        <script>
             var cartItem = `{{product.id}}`
            var data = {
                cartItem: cartItem
            };
             var url2 = "remove_from_cart/"
        </script>
        <p></p>
        <div float="right">
        <button background-color='#f44336' width="18em" class= "btn btn-danger btn-md my-0 p" onClick="removeData(url2, data);">Remove from cart
            <i class="fas fa-shopping-cart ml-1"></i>
        </button> 
       
        </div>
        <p></p>
        <div float="right">
        <a background-color='#e7e7e7'color= "black" href="{% url 'shop:shopping_cart' %}" class="btn" >Cart
            <i class="fas fa-shopping-cart ml-1"></i>
        </a> 
    </div> 
        <p></p>
        <ul>
        <H5> <b>About this item </b></H5>
        <li> <b>Price: </b>{{ object.price }} €</li>        
        <li> <b> Description: </b>{{ object.description }}</li>
    </ul>

    </div>
</div>       

            {% comment %} 
            <form id="cart_item" class="d-flex justify-content-left" method="POST">
              <input type="number" value="1" id="cart_item" aria-label="Search" class="form-control" style="width: 100px">
            
            
            </form> {% endcomment %}

          </div>
        </div>
      </div>
      <hr>
    </div>
    <div>
        {% if items %}
        <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{items}}</span>
          </h4>
          {% endif %}
    </div>

    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>

    <script>
  
        console.log(`{{product.id}}`)
        function postData(url, data) {
  // Default options are marked with *
  $.ajax({
    type: "GET",
    url: url,
    data: data,
    success: function(data){
        console.log("success");
        console.log(data);
        location.reload();
        window.location.href = "{% url 'shop:shopping_cart'%}" ;
        // document.getElementById("add_button").onclick = function () {
        //         location.href = "{% url 'shop:shopping_cart'%}" ;
        //     }
    },
    failure: function(data){
        console.log("failure");
        console.log(data);
    },
});
}
    
function removeData(url2, data) {
  // Default options are marked with *
  $.ajax({
    type: "GET",
    url: url2,
    data: data,
    success: function(data){
        console.log("success");
        console.log(data);
    },
    failure: function(data){
        console.log("failure");
        console.log(data);
    },
});
}
    </script>
     </main>

{% endblock content %}

Webshop/templates/shopping_cart.html
{% extends "base.html" %}
{% load static %}   

{% block content %}
<style>
    p {
    font-size: large;
}
.box {
  border : 1px solid black;
  width: 300px;
  padding-top: 5px;
  padding-left: 5px;
  padding-bottom: 5px;
  padding-right: 5px;
  float:right;
}
.div_subtotal {
  padding: 30px;
  border: 1px solid #4CAF50;

}
.right {
  position: relative;
  right: 5px;
  width: 300px;
  border: 3px solid #73AD21;
  padding: 10px;
}
    </style>
<H3> Shopping Cart</H3>
<table summary="Your Shopping Cart" class="table table-bordered" id="shopping_cart">

    <thead class="thead-dark">
    <tr>

        <th scope="col"></th>
        <th scope="col">Product name</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col" width="2px">Product Code</th>
    
    </tr>
    </thead>
    <tbody>
      <script>
        let pk
      </script>
        {%  for item in object.products.all  %}
          <script>
            
          </script>
           <tr>
            <td><img src="{{item.product.image.url}}" alt="product" width="50" height="70"  class="img-fluid" ></td>
               <td> {{item.product.product_name.title}}</td>
               <td> {{item.product.price}} €</td>
               <td> {{item.quantity}}
                <td> {{item.product.code}}</td>
    
              </script>
   
          
               </td>
               <script>
                pk = `{{item.product.id}}`
                console.log("pk", pk)
            </script>
           </tr>
        {% endfor %}
        <form>
          <div class="box">
          <b>Product name or code: </b>
          <br>
          <input type="text" placeholder="product name or code" id="product_name">
            <br>
          <b>Quantity: </b> 
          <br>
          <input type="text" placeholder="qty" id="quantity">
            <br>
          <button type="button" onclick="postQuantity(pk);">Update Quantity</button>
          </div>
        </form>

        <tr>
            <td colspan="5">
                <a href="{% url 'shop:checkout' %}" class="btn btn-warning float-right ml-2">Checkout</a>
                <a href="/" class="btn btn-primary float-right">Continue Shopping</a>
            </td>
        </tr>
    </tbody>
   </table> 
   <div float="right"  padding= "30px" class="div_subtotal">
      <p font-size ="large"style="text-align:right" >Subtotal: <b> {{object.get_total_amount}} €<p> </b><tr>
</div>

<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
              <script>
function postQuantity(pk) {
  var quantity= document.getElementById("quantity").value
   
  var product_name = document.getElementById("product_name").value
    var data = {product_name:product_name, quantity: quantity};
  $.ajax({
    type: "GET",
    url: `update_quantity/`,
    data: JSON.stringify(data),
    success: function(data){
        console.log("success");
        location.reload();
        console.log(JSON.stringify(data));
    },
    failure: function(data){
        console.log("failure");
        console.log(data);
    },
});
}
</script>
   {% endblock content %}
   